apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-detection-service
  namespace: argocd
spec:
  project: risk
  source:
    repoURL: https://github.com/KrushnaBhujbal/finops-banking-platform.git
    targetRevision: main
    path: helm/charts/generic-microservice
    helm:
      valueFiles:
        - "../../values/dev/fraud-detection-service.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: risk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
