apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wire-transfer-service
  namespace: argocd
spec:
  project: payments
  source:
    repoURL: https://github.com/KrushnaBhujbal/finops-banking-platform.git
    targetRevision: main
    path: helm/charts/generic-microservice
    helm:
      valueFiles:
        - "../../values/dev/wire-transfer-service.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: payments
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
